
const SONGS =

[
    ['entries/Adrien Milliard - PurPLL Entry/Extranormal music box-PurPLL Contest.mp3', 'entries/Adrien Milliard - PurPLL Entry/Contact info PLL.txt'], 
    ['entries/Alan Holt - Submission from Alan Holt/PURPLL Trips.mp3', 'entries/Alan Holt - Submission from Alan Holt/Purpll sample pack contest submission from Alan Holt.txt'], 
    ['entries/Alessandro Notari - Montreal by Ela Iràton/Montreal.mp3', 'entries/Alessandro Notari - Montreal by Ela Iràton/Montreal - Ela Iràton.txt'], 
    ['entries/Andrew Martin/Andrew Martin - mtl_asm_collage2_andrewmartin.mp3', 'entries/Andrew Martin/Andrew Martin - andrew_martin_collage.txt'], 
    ['entries/Becca  Stevens - Jan Esbra Purppl sub/purpl 2 final.mp3', 'entries/Becca  Stevens - Jan Esbra Purppl sub/purpplsubmissionJanEsbra.txt'], 
    ['entries/Ben Bowman - PurPLL Chatterer Box benbowman97@hotmail.com/May12.21PurPLL Chatterer Box.wav', 'entries/Ben Bowman - PurPLL Chatterer Box benbowman97@hotmail.com/PurPLL Chatterer Box Entry.txt'], 
    ['entries/BoterBoter/BoterBoter - Daans Daans - Lick your Darlings By BoterBoter.mp3', 'entries/BoterBoter/BoterBoter.txt'], 
    ['entries/Bryan Elyo/Brian Elyo - MOBDIVIDUAL - Brian Elyo - I HOPE I WIN PURPLL.m4a', 'entries/Bryan Elyo/Brian Elyo - mobdividual - brian elyo - i hope i win purpll.txt'], 
    ['entries/D. Tilbury/D. Tilbury (that_s my pen-name....real name is[] J. Norton) - Purpll Python Passion Part-1 and Plutonic Panting Passion Part-2.mp3', 'entries/D. Tilbury/D. Tilbury (that_s my pen-name....real name is[] J. Norton) - pppp1_pppp2_readme.txt'], 
    ['entries/Dan O_Grady/Dan O_Grady - ppl who need ppl.mp3', 'entries/Dan O_Grady/Dan O_Grady - ppl who love ppl.txt'], 
    ['entries/Dave Ruckstuhl/Dave Ruckstuhl - druckstuhl PURPLL.mp3', 'entries/Dave Ruckstuhl/Dave Ruckstuhl - druckstuhl PURPLL.txt'], 
    ['entries/Devon Ferucci/devon ferrucci - (swimming) mtl asm purp.1.mp3', 'entries/Devon Ferucci/devon ferrucci - purp.txt'], 
    ['entries/Ed Osborne/Ed Osborn - Osborn_Nondognon.mp3', 'entries/Ed Osborne/Ed Osborn - Osborn_Nondognon_Notes.txt'], 
    ['entries/finn - traint purpll entry/gambas pll pll (mtl.asm rmx).mp3', 'entries/finn - traint purpll entry/gambas pll pll.txt'], 
    ['entries/François-Gabriel Marcotte - Do U luv me Jamie Stewart/Do U luv me Jamie Stewart_!__ mp3.mp3', 'entries/François-Gabriel Marcotte - Do U luv me Jamie Stewart/giveaway text.txt'], 
    ['entries/Fredrik Holmer/Fredrik Holmér - PURPLL.mp3', 'entries/Fredrik Holmer/Fredrik Holmér - text.txt'], 
    ['entries/Giles Hoey - purpll drone/Monasgil.mp3', 'entries/Giles Hoey - purpll drone/purpll text.txt'], 
    ['entries/Harold Camacho/PURPLL Sky.wav', 'entries/Harold Camacho/HC.txt'], 
    ['entries/James Bernardo/James Bernardo - Purppl Dream.mp3', 'entries/James Bernardo/James Bernardo - PurpplDream.txt'], 
    ['entries/Jason Borga/Jason Borga - borga_prplgltch.mp3', 'entries/Jason Borga/Jason Borga - purpllcontest.txt'], 
    ['entries/Jeff Mawer - Montreal Assembly PURPLL Sweepstakes Submission/Jefre Erick - PURPLL one v3.mp3', 'entries/Jeff Mawer - Montreal Assembly PURPLL Sweepstakes Submission/PURPLL Sweepstake Contact Info.txt'], 
    ['entries/Joe Strutt/Joe Strutt - purpll contest entry - Joe Strutt.mp3', 'entries/Joe Strutt/Joe Strutt - purpll contest entry - Joe Strutt.txt'], 
    ['entries/John - PURPLL Pizza/Step.4D.purpll.pizza.mp3', 'entries/John - PURPLL Pizza/purpll PIZZA.txt'], 
    ['entries/Jonathan Calzo - Tenshun mtlasm purpll beat/mtlasm purpll beat sample contest.mp3', 'entries/Jonathan Calzo - Tenshun mtlasm purpll beat/mtl.asm purpll beat text.txt'], 
    ['entries/Jonathan Demers/Jonathan Demers - Yes WIth A Capital S - -Finger Guns- MTL ASM entry.mp3', 'entries/Jonathan Demers/Jonathan Demers - MTL ASM entry - Jonathan Demers.txt'], 
    ['entries/Juan Castro Zuzuarregui/Juan Castro Zuzuarregui - i_m always looking for john cage .mp3', 'entries/Juan Castro Zuzuarregui/Juan Castro Zuzuarregui - Juan Castro Zuzuarregui.txt'], 
    ['entries/Justin Hrabovsky - Justin Hrabovsky PURPLL Sample Pack Submission/Location Scout - PURPLL Motif.mp3', 'entries/Justin Hrabovsky - Justin Hrabovsky PURPLL Sample Pack Submission/Location Scout - PURPLL Motif (Info).txt'], 
    ['entries/Kaine Harington/Kaine Harington - American French Fries - PurPLL Hell Beat.mp3', 'entries/Kaine Harington/Kaine Harington - PurPLL Hell Beat.txt'], 
    ['entries/Lars Bjork - Mapping the void/Mapping the void.mp3', 'entries/Lars Bjork - Mapping the void/Hi MTL.txt'], 
    ['entries/Michael Rey - PURPPL - Everything Moves/PURPPL - Everything Moves.mp3', 'entries/Michael Rey - PURPPL - Everything Moves/PURPPLLinerNotes.txt'], 
    ['entries/Mike Kay/Mike Kay - Hetlandensis-Mike_Kay.mp3', 'entries/Mike Kay/Mike Kay - Hetlandensis-Mike_Kay.txt'], 
    ['entries/Morgan Tindall - Dinky Mirage Submission/Dinky Mirage - Victim and PURPLLtrator.mp3', 'entries/Morgan Tindall - Dinky Mirage Submission/Dinky Mirage INFO.txt'], 
    ['entries/Nicholas Wilson/Nicholas Wilson - PURPLL.mp3', 'entries/Nicholas Wilson/NicolasWilson.txt'], 
    ['entries/Nik Viola/Nik Viola - repurpllsd.mp3', 'entries/Nik Viola/Nik Viola - repurpllsd.txt'], 
    ['entries/Nikita - prpl by N/prpl.mp3', 'entries/Nikita - prpl by N/prpl.txt'], 
    ['entries/Pascal Normand/Pascal Normand - Purple Chaos (Mtl Assy).mp3', 'entries/Pascal Normand/Pascal Normand - Purple Chaos.txt'], 
    ['entries/Paulo Cezar Gabrielleschi - purpll red/GABRIELLESCHI - Purpll Red ___ mix 9thMay2021_b.wav', 'entries/Paulo Cezar Gabrielleschi - purpll red/Paulo Cezar Gabrielleschi - gabrielleschi purpll red info.txt'], 
    ['entries/Preston Chin - GRAPE CRUSH (Preston)/GRAPE CRUSH (Preston).mp3', 'entries/Preston Chin - GRAPE CRUSH (Preston)/GRAPE CRUSH (Preston) - mtl.asm.txt'], 
    ['entries/Quentin Leonetti/Quentin Leonetti - Quentin Leonetti - fun times with purpll samples.mp3', 'entries/Quentin Leonetti/Quentin Leonetti - quentin leonetti - purpll.txt'], 
    ['entries/Ross Henteleff/Ross Henteleff - mtl assembly submission.mp3', 'entries/Ross Henteleff/Ross Henteleff - mtl assmebly note.txt'], 
    ['entries/Samuel Boldrini/Samuel Boldrini - Balldreaming - mtlasm3.mp3', 'entries/Samuel Boldrini/SamuelBoldrini.txt'], 
    ['entries/Simon Williams/Simon Williams - Psy Why_The Cave.mp3', 'entries/Simon Williams/Simon Williams - Psy Why - MTL PURPLL CONTEST INFO.txt'], 
    ['entries/Stehen Straus/Stephen Straus - GIMME A TREAT.mp3', 'entries/Stehen Straus/StephenStraus.txt'], 
    ['entries/Stepan - hlst.mtl.asm.cntst/mtl.asm.cntst.mp3', 'entries/Stepan - hlst.mtl.asm.cntst/dtls.txt'], 
    ['entries/the color moxie - The Color Moxie - mtl.asm/Color Moxie - MTL ASM.mp3', 'entries/the color moxie - The Color Moxie - mtl.asm/theColorMoxie.txt'], 
    ['entries/Tom Thompson/Tom Thompson - mtl.asm contest Tom Thompson.mp3', 'entries/Tom Thompson/Tom Thompson - Mtl.asm Contest.txt'], 
    ['entries/Will/Will - purpllgolld-2021.mp3', 'entries/Will/Will - purpllgolld2021.txt'], 
    ['entries/Willem Zenhorst/Willem Zenhorst - Willem Zenhorst - PurPLLto5 (drone improv).mp3', 'entries/Willem Zenhorst/Willem Zenhorst - Willem Zenhorst - PurPLLto5 (drone improv).txt'], 
    ['entries/William Ferris - Matthew LaBarbera - Nexium/Nexium.mp3', 'entries/William Ferris - Matthew LaBarbera - Nexium/Nexium.txt'], 
    ['entries/William Scott Thompson/William Scott Thompson - wst_purpll.mp3', 'entries/William Scott Thompson/William Scott Thompson - wst_purpll.txt'], 
  ]
  